/** Instrument Panel design system: device-local volume deck with clearly labelled preview telemetry. */
import { CalendarDays, Clock3, Flame, Gauge, LineChart, TimerReset, TrendingUp } from "lucide-react";
import AppFrame from "@/components/AppFrame";

const weeklyWords = [32, 48, 42, 72, 55, 87, 64];
const monthlyPace = [42, 47, 45, 56, 58, 66];

export default function Analytics() {
  return <AppFrame title="Analytics — local telemetry"><section className="page-heading"><div><span className="eyebrow">LOCAL VOLUME DECK</span><h1>Measure attention, not surveillance.</h1><p>These charts are a browser-only preview. They become personal as local reading sessions accumulate.</p></div><span className="analytics-badge"><LineChart size={17} /> Local preview</span></section><section className="metric-grid analytics-metrics"><article><TrendingUp size={18} /><span>Words read</span><b>12.6k</b><em>Preview total</em></article><article><CalendarDays size={18} /><span>Active days</span><b>5 <small>OF 7</small></b><em>This week</em></article><article><Clock3 size={18} /><span>Focus time</span><b>2h 14m</b><em>Preview total</em></article><article><Gauge size={18} /><span>Average WPM</span><b>782</b><em>Preview pace</em></article></section><section className="analytics-grid"><article className="chart-card"><div className="chart-card__header"><div><span className="eyebrow">WEEKLY VOLUME</span><h2>Words read</h2></div><span>12,624 total</span></div><div className="chart-bars">{weeklyWords.map((height, index) => <div key={index}><i style={{ height: `${height}%` }} /><span>{["SUN","MON","TUE","WED","THU","FRI","SAT"][index]}</span></div>)}</div></article><article className="chart-card"><div className="chart-card__header"><div><span className="eyebrow">MONTHLY PACE</span><h2>Average WPM</h2></div><span>MAR — AUG</span></div><svg className="pace-chart" viewBox="0 0 420 190" role="img" aria-label="Preview line graph for average WPM from March to August"><path d="M20 147 L96 128 L172 137 L248 89 L324 78 L400 39" fill="none" stroke="var(--signal)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="M20 147 L96 128 L172 137 L248 89 L324 78 L400 39 L400 170 L20 170 Z" fill="var(--signal-soft)"/>{monthlyPace.map((_, index) => <circle key={index} cx={20 + index * 76} cy={[147,128,137,89,78,39][index]} r="5" fill="var(--panel-solid)" stroke="var(--signal)" strokeWidth="3" />)}</svg><div className="chart-months"><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span><span>JUL</span><span>AUG</span></div></article></section><section className="analytics-summary"><div><TimerReset size={19} /><span><b>Finish estimate</b><small>At 782 WPM, a 60k-word book takes roughly 77 minutes of active reader time.</small></span></div><div><Flame size={19} /><span><b>Consistency signal</b><small>Session history will gradually replace this preview with your device-local pattern.</small></span></div></section></AppFrame>;
}
