/** Instrument Panel design system: precision status console with calibrated, device-local reading states. */
import { ArrowUpRight, BookOpen, CircleDot, Clock3, Flame, Gauge, Play, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import AppFrame from "@/components/AppFrame";

const previewBars = [28, 44, 38, 65, 48, 76, 59];
const metrics = [
  { icon: Gauge, label: "PACE SETPOINT", value: "900", unit: "WPM", detail: "stored preference", index: "01" },
  { icon: BookOpen, label: "SESSION WORDS", value: "1,468", unit: "", detail: "local counter", index: "02" },
  { icon: Clock3, label: "FOCUS TIMER", value: "18", unit: "MIN", detail: "active device", index: "03" },
  { icon: Flame, label: "READING CONTINUITY", value: "4", unit: "DAYS", detail: "local activity", index: "04" },
];

export default function Dashboard() {
  return <AppFrame title="Dashboard — local session"><div className="dashboard-console"><section className="page-heading dashboard-heading"><div><span className="eyebrow">DEVICE-LOCAL / READING STATUS</span><h1>Reading session staged.</h1><p>Document position, pace, and focus time are calibrated on this device.</p></div><div className="dashboard-heading__action"><span className="dashboard-focus-lock"><CircleDot size={14} /> Focus lock · 019%</span><Link href="/pacing-engine" className="primary-cta"><Play size={16} fill="currentColor" /> Resume at position</Link></div></section><section className="metric-grid" aria-label="Local reading instrument readings">{metrics.map(({ icon: Icon, label, value, unit, detail, index }) => <article key={label} className="instrument-readout"><div className="instrument-readout__head"><Icon size={17} /><span>{label}</span><i>{index}</i></div><b>{value} {unit && <small>{unit}</small>}</b><em>{detail}</em></article>)}</section><section className="dashboard-grid"><article className="resume-card resume-card--active"><div className="resume-card__top"><span className="eyebrow">ACTIVE DOCUMENT / HANDOFF</span><ShieldCheck size={17} /></div><div className="resume-card__position"><span>POSITION</span><b>019%</b><i>FOCUS ANCHOR</i></div><h2>Atomic Habits</h2><p>Chapter 1 · session handoff ready</p><div className="document-progress"><span style={{ width: "19%" }} /><i aria-hidden="true" /></div><div className="resume-card__footer"><span>08:16 remaining</span><Link href="/pacing-engine">Resume sequence <ArrowUpRight size={14} /></Link></div></article><article className="velocity-card"><div><span className="eyebrow">SEVEN-DAY INPUT / LOCAL</span><h2>Pace profile holding steady.</h2></div><div className="preview-bars" aria-label="Preview local reading activity"><div className="preview-bars__columns">{previewBars.map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="preview-bars__labels"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span></div></div></article></section><section className="privacy-panel"><ShieldCheck size={21} /><div><b>DEVICE-LOCAL STATUS / ACTIVE</b><p>Reading files and session preferences remain on this device. Exporting data is always deliberate.</p></div><Link href="/library">Inspect library <ArrowUpRight size={15} /></Link></section></div></AppFrame>;
}
