/** Instrument Panel design system: dashboard showing local progress surfaces without remote telemetry. */
import { ArrowUpRight, BookOpen, Clock3, Flame, Gauge, Play, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import AppFrame from "@/components/AppFrame";

const previewBars = [28, 44, 38, 65, 48, 76, 59];

export default function Dashboard() {
  return <AppFrame title="Dashboard — local session"><section className="page-heading"><div><span className="eyebrow">DEVICE-LOCAL DASHBOARD</span><h1>Pick up where focus left off.</h1><p>Every metric shown here is computed in this browser. Connect nothing to keep reading.</p></div><Link href="/pacing-engine" className="primary-cta"><Play size={16} fill="currentColor" /> Resume reader</Link></section><section className="metric-grid"><article><Gauge size={18} /><span>Current pace</span><b>900 <small>WPM</small></b><em>Reader preference</em></article><article><BookOpen size={18} /><span>Words in this session</span><b>1,468</b><em>Local preview</em></article><article><Clock3 size={18} /><span>Focus time</span><b>18 <small>MIN</small></b><em>Current device</em></article><article><Flame size={18} /><span>Reading streak</span><b>4 <small>DAYS</small></b><em>Local activity</em></article></section><section className="dashboard-grid"><article className="resume-card"><div className="resume-card__top"><span className="eyebrow">ACTIVE DOCUMENT</span><ShieldCheck size={17} /></div><h2>Atomic Habits</h2><p>Chapter 1 · 19% complete</p><div className="document-progress"><span style={{ width: "19%" }} /></div><div className="resume-card__footer"><span>08:16 remaining</span><Link href="/pacing-engine">Continue <ArrowUpRight size={14} /></Link></div></article><article className="velocity-card"><div><span className="eyebrow">WEEKLY VELOCITY</span><h2>Steady intake, not a sprint.</h2></div><div className="preview-bars" aria-label="Preview local reading activity"><div className="preview-bars__columns">{previewBars.map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="preview-bars__labels"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span></div></div></article></section><section className="privacy-panel"><ShieldCheck size={21} /><div><b>Local-first status: active</b><p>Reading files and session preferences remain on this device. Exporting data is always a deliberate action.</p></div><Link href="/library">Open library <ArrowUpRight size={15} /></Link></section></AppFrame>;
}
